FROM golang:1.19 AS builder

COPY . /src
WORKDIR /src

RUN make build

FROM alpine:latest

COPY --from=builder /src/bin /app
COPY static /app/static

WORKDIR /app

EXPOSE 8000
EXPOSE 9000
EXPOSE 13000
VOLUME /data/conf

CMD ["./server", "-conf", "/data/conf"]
